import 'package:flutter/foundation.dart';
import '../models/genre.dart';import '../models/page_result.dart';import '../models/publisher.dart';import '../models/reader.dart';import '../models/simple_query.dart';import '../repositories/genre_repository.dart';import '../repositories/publisher_repository.dart';import '../repositories/reader_repository.dart';import 'load_status.dart';

abstract class BaseReferenceNotifier<T> extends ChangeNotifier {
  SimpleQuery query=const SimpleQuery(); PageResult<T> result=PageResult.empty(); LoadStatus status=LoadStatus.idle; String? error; final Set<int> selected={};
  bool get hasSelection=>selected.isNotEmpty;
  Future<PageResult<T>> find(SimpleQuery q); Future<T?> findById(int id); Future<void> softDeleteRepo(int id); Future<void> hardDeleteRepo(int id); Future<void> restoreRepo(int id); Future<int> deleteManyRepo(List<int> ids);
  Future<void> applyQuery(SimpleQuery q)async{if(q!=query){query=q;selected.clear();}await load();}
  Future<void> load()async{status=LoadStatus.loading;error=null;notifyListeners();try{result=await find(query);status=LoadStatus.success;}catch(e){error='Не удалось загрузить список: $e';status=LoadStatus.error;}notifyListeners();}
  void toggleSelection(int id){selected.contains(id)?selected.remove(id):selected.add(id);notifyListeners();}
  Future<void> softDelete(int id)async{await softDeleteRepo(id);await load();} Future<void> hardDelete(int id)async{await hardDeleteRepo(id);await load();} Future<void> restore(int id)async{await restoreRepo(id);await load();} Future<void> deleteSelected()async{await deleteManyRepo(selected.toList());selected.clear();await load();}
}
class GenreListNotifier extends BaseReferenceNotifier<Genre>{final GenreRepository repo;GenreListNotifier(this.repo);@override Future<PageResult<Genre>> find(SimpleQuery q)=>repo.find(q);@override Future<Genre?> findById(int id)=>repo.findById(id);@override Future<void> softDeleteRepo(int id)=>repo.softDelete(id);@override Future<void> hardDeleteRepo(int id)=>repo.hardDelete(id);@override Future<void> restoreRepo(int id)=>repo.restore(id);@override Future<int> deleteManyRepo(List<int> ids)=>repo.deleteMany(ids);Future<Genre> create(Genre v)async{final x=await repo.create(v);await load();return x;}Future<Genre> update(Genre v)async{final x=await repo.update(v);await load();return x;}}
class PublisherListNotifier extends BaseReferenceNotifier<Publisher>{final PublisherRepository repo;PublisherListNotifier(this.repo);@override Future<PageResult<Publisher>> find(SimpleQuery q)=>repo.find(q);@override Future<Publisher?> findById(int id)=>repo.findById(id);@override Future<void> softDeleteRepo(int id)=>repo.softDelete(id);@override Future<void> hardDeleteRepo(int id)=>repo.hardDelete(id);@override Future<void> restoreRepo(int id)=>repo.restore(id);@override Future<int> deleteManyRepo(List<int> ids)=>repo.deleteMany(ids);Future<Publisher> create(Publisher v)async{final x=await repo.create(v);await load();return x;}Future<Publisher> update(Publisher v)async{final x=await repo.update(v);await load();return x;}}
class ReaderListNotifier extends BaseReferenceNotifier<Reader>{final ReaderRepository repo;ReaderListNotifier(this.repo);@override Future<PageResult<Reader>> find(SimpleQuery q)=>repo.find(q);@override Future<Reader?> findById(int id)=>repo.findById(id);@override Future<void> softDeleteRepo(int id)=>repo.softDelete(id);@override Future<void> hardDeleteRepo(int id)=>repo.hardDelete(id);@override Future<void> restoreRepo(int id)=>repo.restore(id);@override Future<int> deleteManyRepo(List<int> ids)=>repo.deleteMany(ids);Future<Reader> create(Reader v)async{final x=await repo.create(v);await load();return x;}Future<Reader> update(Reader v)async{final x=await repo.update(v);await load();return x;}}
